/* ComfyView: a LiteGraph-styled renderer for ComfyUI workflow JSON.
 * Nodes and groups can be moved, resized and aligned; the layout saves back out.
 * Connections are never edited. */
(function () {
'use strict';

/* ---------------------------------------------------------------- constants */

const TITLE_H = 30;
const SLOT_H = 20;
const WIDGET_H = 20;
const WIDGET_MARGIN = 15;
const COLLAPSED_WIDTH = 80;
const ROUND = 8;
const MIN_W = 80;
const MIN_H = 24;
const HANDLE = 7;          // resize grab tolerance, in screen pixels
const GROUP_MIN_W = 140;
const GROUP_MIN_H = 80;

const C = {
  bg: '#1a1a1a',
  grid: 'rgba(255,255,255,0.035)',
  gridMajor: 'rgba(255,255,255,0.06)',
  nodeColor: '#333',
  nodeBg: '#353535',
  boxColor: '#666',
  titleText: '#999',
  text: '#AAA',
  widgetBg: '#222',
  widgetOutline: '#666',
  widgetText: '#DDD',
  widgetText2: '#999',
  link: '#9A9',
  border: 'rgba(0,0,0,0.85)',
  selected: '#FFF',
  marquee: '#4a9eff',
};

// ComfyUI's link/slot colors per data type.
const TYPE_COLORS = {
  CLIP: '#FFD500',
  CLIP_VISION: '#A8DADC',
  CLIP_VISION_OUTPUT: '#ad7452',
  CONDITIONING: '#FFA931',
  CONTROL_NET: '#6EE7B7',
  IMAGE: '#64B5F6',
  LATENT: '#FF9CF9',
  MASK: '#81C784',
  MODEL: '#B39DDB',
  STYLE_MODEL: '#C2FFAE',
  VAE: '#FF6E6E',
  NOISE: '#B0B0B0',
  GUIDER: '#66FFFF',
  SAMPLER: '#ECB4B4',
  SIGMAS: '#CDFFCD',
  TAESD: '#DCC274',
  INT: '#29699C',
  FLOAT: '#77B5C4',
  STRING: '#8BC34A',
  BOOLEAN: '#D9D9D9',
};

// Widget names for common core nodes, so rows read like the real thing.
// Unknown nodes fall back to value-only rows.
const WIDGETS = {
  KSampler: ['seed', 'control_after_generate', 'steps', 'cfg', 'sampler_name', 'scheduler', 'denoise'],
  KSamplerAdvanced: ['add_noise', 'noise_seed', 'control_after_generate', 'steps', 'cfg', 'sampler_name',
    'scheduler', 'start_at_step', 'end_at_step', 'return_with_leftover_noise'],
  CLIPTextEncode: ['text'],
  CLIPTextEncodeSDXL: ['width', 'height', 'crop_w', 'crop_h', 'target_width', 'target_height', 'text_g', 'text_l'],
  CLIPSetLastLayer: ['stop_at_clip_layer'],
  CheckpointLoaderSimple: ['ckpt_name'],
  UNETLoader: ['unet_name', 'weight_dtype'],
  VAELoader: ['vae_name'],
  LoraLoader: ['lora_name', 'strength_model', 'strength_clip'],
  LoraLoaderModelOnly: ['lora_name', 'strength_model'],
  EmptyLatentImage: ['width', 'height', 'batch_size'],
  EmptySD3LatentImage: ['width', 'height', 'batch_size'],
  LatentUpscale: ['upscale_method', 'width', 'height', 'crop'],
  LatentUpscaleBy: ['upscale_method', 'scale_by'],
  ImageScale: ['upscale_method', 'width', 'height', 'crop'],
  ImageScaleBy: ['upscale_method', 'scale_by'],
  SaveImage: ['filename_prefix'],
  LoadImage: ['image', 'upload'],
  ControlNetLoader: ['control_net_name'],
  ControlNetApply: ['strength'],
  ControlNetApplyAdvanced: ['strength', 'start_percent', 'end_percent'],
  UpscaleModelLoader: ['model_name'],
  ConditioningSetArea: ['width', 'height', 'x', 'y', 'strength'],
  LatentFromBatch: ['batch_index', 'length'],
  RepeatLatentBatch: ['amount'],
  ImageInvert: [],
  VAEDecode: [],
  VAEEncode: [],
  Note: ['text'],
  MarkdownNote: ['text'],
  PrimitiveNode: ['value', 'control_after_generate'],
  Reroute: [],
  ModelSamplingDiscrete: ['sampling', 'zsnr'],
  ModelSamplingFlux: ['max_shift', 'base_shift', 'width', 'height'],
  FluxGuidance: ['guidance'],
  CLIPLoader: ['clip_name', 'type'],
  DualCLIPLoader: ['clip_name1', 'clip_name2', 'type'],
};

/* --------------------------------------------------------------- node packs */

// nodedb.js (generated by tools/build-nodedb.py) maps node types to the custom
// node pack that provides them. Core ComfyUI types are listed separately.
const DB = window.COMFY_NODE_DB || { core: [], packs: [], nodes: {} };
const CORE = new Set(DB.core);

function packsFor(type) {
  const hit = DB.nodes[type];
  if (hit === undefined) return null;
  return (Array.isArray(hit) ? hit : [hit]).map(i => DB.packs[i]).filter(Boolean);
}

function packUrl(short) {
  return short.startsWith('gh:') ? 'https://github.com/' + short.slice(3) : short;
}

// A hand-picked palette first, so the common case of a handful of packs stays
// easy to tell apart; past that, evenly spaced hues at a darker lightness.
const PACK_PALETTE = [
  '#ff5c5c', '#4ade80', '#60a5fa', '#fbbf24', '#c084fc', '#22d3ee',
  '#f472b6', '#a3e635', '#fb923c', '#2dd4bf', '#e879f9', '#93c5fd',
  '#facc15', '#f87171', '#5eead4', '#d8b4fe',
];
function packColor(i) {
  if (i < PACK_PALETTE.length) return PACK_PALETTE[i];
  return `hsl(${((i - PACK_PALETTE.length) * 137.508) % 360}, 65%, 45%)`;
}

const CORE_COLOR = '#7f8c8d';
const UNKNOWN_COLOR = '#e0a33c';

/* ---------------------------------------------------------------- settings */

const SETTINGS_KEY = 'comfyview.settings';
const settings = Object.assign({
  highlight: true,          // pack coloring on the canvas
  labels: true,             // pack name above each non-stock node
  packsPanelClosed: false,  // the panel shows itself until the user closes it
  controlsPanelClosed: false,
}, load());

function load() {
  try { return JSON.parse(localStorage.getItem(SETTINGS_KEY)) || {}; } catch (e) { return {}; }
}
function saveSettings() {
  try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); } catch (e) { /* private mode */ }
}

/* ------------------------------------------------------------------- state */

const canvas = document.getElementById('graph');
const ctx = canvas.getContext('2d');

const view = { x: 0, y: 0, scale: 1 };
let raw = null;            // the original parsed JSON, mutated only for layout
let nodes = [];            // normalised node views
let links = [];            // normalised links
let groups = [];
let order = [];            // draw order (indices into nodes)
let nodeById = new Map();
let selection = new Set(); // selected nodes
let marquee = null;        // active rubber-band rect in graph space
let selectedGroup = null;  // comment box currently picked, for Delete etc.
let report = null;         // { packs, core, unknown }
let dirty = true;
let fileName = 'workflow.json';

/* ---------------------------------------------------------------- utilities */

function typeColor(t) {
  if (!t) return C.link;
  return TYPE_COLORS[String(t).toUpperCase()] || C.link;
}

function sizeOf(s) {
  if (!s) return [140, 60];
  if (Array.isArray(s)) return [s[0], s[1]];
  return [s['0'] ?? s.width ?? 140, s['1'] ?? s.height ?? 60];
}

function roundRect(x, y, w, h, r) {
  const rr = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + rr, y);
  ctx.lineTo(x + w - rr, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + rr);
  ctx.lineTo(x + w, y + h - rr);
  ctx.quadraticCurveTo(x + w, y + h, x + w - rr, y + h);
  ctx.lineTo(x + rr, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - rr);
  ctx.lineTo(x, y + rr);
  ctx.quadraticCurveTo(x, y, x + rr, y);
  ctx.closePath();
}

// Rounded on the given corners only: [tl, tr, br, bl]
function roundRectC(x, y, w, h, r, corners) {
  const [tl, tr, br, bl] = corners.map(c => (c ? Math.min(r, w / 2, h / 2) : 0));
  ctx.beginPath();
  ctx.moveTo(x + tl, y);
  ctx.lineTo(x + w - tr, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + tr);
  ctx.lineTo(x + w, y + h - br);
  ctx.quadraticCurveTo(x + w, y + h, x + w - br, y + h);
  ctx.lineTo(x + bl, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - bl);
  ctx.lineTo(x, y + tl);
  ctx.quadraticCurveTo(x, y, x + tl, y);
  ctx.closePath();
}

function fmtNumber(v) {
  if (typeof v !== 'number') return String(v);
  if (Number.isInteger(v)) return String(v);
  return String(Math.round(v * 1000) / 1000);
}

function ellipsize(text, maxW) {
  if (ctx.measureText(text).width <= maxW) return text;
  let s = text;
  while (s.length > 1 && ctx.measureText(s + '…').width > maxW) s = s.slice(0, -1);
  return s + '…';
}

function toast(msg, isErr) {
  const el = document.createElement('div');
  el.className = 'toast' + (isErr ? ' err' : '');
  el.textContent = msg;
  document.body.appendChild(el);
  setTimeout(() => el.remove(), isErr ? 6000 : 2600);
}

/* ------------------------------------------------------------- graph loading */

function loadWorkflow(data, name) {
  if (!data || !Array.isArray(data.nodes)) {
    if (data && typeof data === 'object' && Object.values(data).some(v => v && v.class_type)) {
      throw new Error('This is an API-format prompt, not a UI workflow. Export with "Save" (not "Save (API format)").');
    }
    throw new Error('Not a ComfyUI workflow: no "nodes" array.');
  }

  raw = data;
  fileName = name || 'workflow.json';
  nodes = [];
  nodeById = new Map();
  selection = new Set();

  for (const n of data.nodes) {
    const [w, h] = sizeOf(n.size);
    const v = {
      raw: n,
      id: n.id,
      type: n.type || 'Node',
      title: n.title || n.type || 'Node',
      x: (n.pos && (n.pos[0] ?? n.pos['0'])) || 0,
      y: (n.pos && (n.pos[1] ?? n.pos['1'])) || 0,
      w: Math.max(w || 140, MIN_W),
      h: Math.max(h || 40, MIN_H),
      color: n.color || C.nodeColor,
      bgcolor: n.bgcolor || C.nodeBg,
      collapsed: !!(n.flags && n.flags.collapsed),
      mode: n.mode || 0,
      inputs: (n.inputs || []).filter(s => s),
      outputs: (n.outputs || []).filter(s => s),
      widgets: buildWidgets(n),
    };
    v.minW = Math.min(140, v.w);
    v.minH = Math.min(contentHeight(v), v.h);
    nodes.push(v);
    nodeById.set(v.id, v);
  }

  links = normaliseLinks(data);
  groups = (data.groups || []).map(g => ({
    raw: g,
    title: g.title || '',
    b: (g.bounding || [0, 0, 100, 100]).slice(),
    color: g.color || '#3f789e',
    font: g.font_size || 24,
  }));

  order = nodes.map((_, i) => i);
  analysePacks();
  document.getElementById('drop').classList.add('hidden');
  document.getElementById('info').textContent =
    `${fileName}: ${nodes.length} nodes, ${links.length} links` + (groups.length ? `, ${groups.length} groups` : '') +
    (report.packs.length ? `, ${report.packs.length} node pack${report.packs.length > 1 ? 's' : ''}` : '');
  fit();
}

function normaliseLinks(data) {
  const out = [];
  for (const l of (data.links || [])) {
    let id, from, fromSlot, to, toSlot, type;
    if (Array.isArray(l)) {
      [id, from, fromSlot, to, toSlot, type] = l;
    } else if (l && typeof l === 'object') {
      id = l.id;
      from = l.origin_id; fromSlot = l.origin_slot;
      to = l.target_id; toSlot = l.target_slot;
      type = l.type;
    } else continue;
    out.push({ id, from, fromSlot: fromSlot | 0, to, toSlot: toSlot | 0, type });
  }
  return out;
}

function buildWidgets(n) {
  let values = n.widgets_values;
  if (values && !Array.isArray(values) && typeof values === 'object') values = Object.values(values);
  if (!Array.isArray(values) || !values.length) return [];

  const names = WIDGETS[n.type] || null;
  // Widgets converted to input slots are drawn as slots, not rows.
  const converted = new Set((n.inputs || [])
    .filter(s => s && (s.widget || s.widget === ''))
    .map(s => (s.widget && s.widget.name) || s.name));

  // Every widget was dragged out into an input slot, so the node body has no
  // rows at all. True of things like ConcatStringSingle, whose stored height
  // leaves no room for any.
  if (converted.size && converted.size >= values.length) return [];

  const rows = [];
  for (let i = 0; i < values.length; i++) {
    const name = names && i < names.length ? names[i] : null;
    if (name && converted.has(name)) continue;
    const v = values[i];
    if (v === null || v === undefined) continue;
    rows.push({ name, value: v, kind: widgetKind(name, v) });
  }

  // widgets_values holds every widget, converted ones included, so ComfyUI draws
  // exactly (values - converted) rows. When the node's widget names are unknown
  // we cannot tell which ones were converted, but we can still honour the count.
  const budget = values.length - converted.size;
  if (rows.length > budget) rows.length = Math.max(0, budget);
  return rows;
}

function widgetKind(name, v) {
  if (typeof v === 'boolean') return 'toggle';
  if (typeof v === 'number') return 'number';
  if (typeof v === 'string' && (v.includes('\n') || v.length > 48)) return 'text';
  if (name === 'text' || name === 'text_g' || name === 'text_l') return 'text';
  return 'combo';
}

/* ------------------------------------------------------------- pack analysis */

/* Work out which pack every node comes from, and build the report model.
 * Packs are ordered by how many nodes they contribute, so the biggest
 * dependency always gets the first color. */
function analysePacks() {
  const byPack = new Map();
  const core = new Map();
  const unknown = new Map();

  for (const n of nodes) {
    if (CORE.has(n.type)) {
      core.set(n.type, (core.get(n.type) || 0) + 1);
      n.packKey = null;
      n.packName = null;
      continue;
    }
    const found = packsFor(n.type);
    if (!found) {
      unknown.set(n.type, (unknown.get(n.type) || 0) + 1);
      n.packKey = '?';
      n.packName = 'unrecognised';
      continue;
    }
    const key = found[0][1];
    let p = byPack.get(key);
    if (!p) {
      p = { key, title: found[0][0], url: packUrl(key), types: new Map(), count: 0, alt: new Set() };
      byPack.set(key, p);
    }
    p.count++;
    p.types.set(n.type, (p.types.get(n.type) || 0) + 1);
    for (let i = 1; i < found.length; i++) p.alt.add(found[i][0]);
    n.packKey = key;
    n.packName = p.title;
  }

  const packs = [...byPack.values()].sort((a, b) => b.count - a.count || a.title.localeCompare(b.title));
  packs.forEach((p, i) => { p.color = packColor(i); });
  const colorByKey = new Map(packs.map(p => [p.key, p.color]));
  for (const n of nodes) {
    n.packColor = n.packKey === '?' ? UNKNOWN_COLOR : (n.packKey ? colorByKey.get(n.packKey) : null);
  }

  report = {
    packs,
    core: [...core.entries()].sort((a, b) => b[1] - a[1]),
    unknown: [...unknown.entries()].sort((a, b) => b[1] - a[1]),
  };
  renderReport();
}

/* -------------------------------------------------------------- slot layout */

function nodeW(n) { return n.collapsed ? collapsedWidth(n) : n.w; }
function nodeH(n) { return n.collapsed ? 0 : n.h; }

function slotPos(node, isInput, i) {
  if (node.collapsed) {
    const w = collapsedWidth(node);
    return isInput ? [node.x, node.y - TITLE_H / 2] : [node.x + w, node.y - TITLE_H / 2];
  }
  const x = isInput ? node.x + SLOT_H * 0.5 : node.x + node.w + 1 - SLOT_H * 0.5;
  return [x, node.y + (i + 0.7) * SLOT_H];
}

function collapsedWidth(node) {
  ctx.font = '14px Arial';
  return Math.max(COLLAPSED_WIDTH, ctx.measureText(node.title).width + 40);
}

/* The smallest a node may be dragged: enough for its slots and widget rows.
 * Never larger than the size the file already gave it, so nothing jumps. */
function contentHeight(n) {
  let h = Math.max(n.inputs.length, n.outputs.length) * SLOT_H + 4;
  for (const rw of n.widgets) h += (rw.kind === 'text' ? 42 : WIDGET_H) + 4;
  return Math.max(MIN_H, h + 4);
}

function widgetsStartY(node) {
  const rows = Math.max(node.inputs.length, node.outputs.length);
  return rows * SLOT_H + 4;
}

/* ------------------------------------------------------------------ drawing */

function resize() {
  const dpr = window.devicePixelRatio || 1;
  canvas.width = Math.floor(innerWidth * dpr);
  canvas.height = Math.floor(innerHeight * dpr);
  canvas.style.width = innerWidth + 'px';
  canvas.style.height = innerHeight + 'px';
  dirty = true;
}

function draw() {
  if (dirty) {
    dirty = false;
    render();
  }
  requestAnimationFrame(draw);
}

function render() {
  const dpr = window.devicePixelRatio || 1;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.fillStyle = C.bg;
  ctx.fillRect(0, 0, innerWidth, innerHeight);

  drawGrid();

  ctx.save();
  ctx.translate(view.x, view.y);
  ctx.scale(view.scale, view.scale);

  for (const g of groups) drawGroup(g);
  for (const l of links) drawLink(l);
  for (const i of order) drawNode(nodes[i]);
  if (selection.size) for (const i of order) drawSelectionRing(nodes[i]);
  if (settings.labels) for (const i of order) drawPackLabel(nodes[i]);

  ctx.restore();

  if (marquee) drawMarquee();
}

function drawGrid() {
  const step = 50 * view.scale;
  if (step < 6) return;
  const ox = view.x % step, oy = view.y % step;
  ctx.lineWidth = 1;
  ctx.strokeStyle = C.grid;
  ctx.beginPath();
  for (let x = ox; x < innerWidth; x += step) { ctx.moveTo(x + 0.5, 0); ctx.lineTo(x + 0.5, innerHeight); }
  for (let y = oy; y < innerHeight; y += step) { ctx.moveTo(0, y + 0.5); ctx.lineTo(innerWidth, y + 0.5); }
  ctx.stroke();

  const big = step * 5;
  if (big < 24) return;
  const bx = view.x % big, by = view.y % big;
  ctx.strokeStyle = C.gridMajor;
  ctx.beginPath();
  for (let x = bx; x < innerWidth; x += big) { ctx.moveTo(x + 0.5, 0); ctx.lineTo(x + 0.5, innerHeight); }
  for (let y = by; y < innerHeight; y += big) { ctx.moveTo(0, y + 0.5); ctx.lineTo(innerWidth, y + 0.5); }
  ctx.stroke();
}

function drawMarquee() {
  const x = view.x + Math.min(marquee.x0, marquee.x1) * view.scale;
  const y = view.y + Math.min(marquee.y0, marquee.y1) * view.scale;
  const w = Math.abs(marquee.x1 - marquee.x0) * view.scale;
  const h = Math.abs(marquee.y1 - marquee.y0) * view.scale;
  ctx.fillStyle = 'rgba(74,158,255,0.12)';
  ctx.fillRect(x, y, w, h);
  ctx.strokeStyle = C.marquee;
  ctx.lineWidth = 1;
  ctx.strokeRect(x + 0.5, y + 0.5, w, h);
}

function drawGroup(g) {
  const [x, y, w, h] = g.b;
  ctx.globalAlpha = 0.5;
  ctx.fillStyle = g.color;
  roundRect(x, y, w, h, ROUND);
  ctx.fill();
  ctx.globalAlpha = 1;

  ctx.strokeStyle = g.color;
  ctx.lineWidth = 2;
  ctx.stroke();

  if (selectedGroup === g) {
    const gap = Math.max(4, 5 / view.scale);
    ctx.save();
    roundRect(x - gap, y - gap, w + gap * 2, h + gap * 2, ROUND + gap);
    ctx.strokeStyle = 'rgba(0,0,0,0.75)';
    ctx.lineWidth = Math.max(5, 6 / view.scale);
    ctx.stroke();
    ctx.strokeStyle = C.selected;
    ctx.lineWidth = Math.max(2.5, 3.5 / view.scale);
    ctx.stroke();
    ctx.restore();
  }

  ctx.fillStyle = g.color;
  ctx.font = `${g.font}px Arial`;
  ctx.textAlign = 'left';
  ctx.textBaseline = 'alphabetic';
  ctx.fillText(g.title, x + 6, y + g.font);

  // resize grip, bottom-right
  ctx.globalAlpha = 0.6;
  ctx.beginPath();
  ctx.moveTo(x + w, y + h - 14);
  ctx.lineTo(x + w, y + h);
  ctx.lineTo(x + w - 14, y + h);
  ctx.closePath();
  ctx.fill();
  ctx.globalAlpha = 1;
}

function drawLink(l) {
  const a = nodeById.get(l.from);
  const b = nodeById.get(l.to);
  if (!a || !b) return;
  const [x1, y1] = slotPos(a, false, l.fromSlot);
  const [x2, y2] = slotPos(b, true, l.toSlot);

  const dist = Math.max(40, Math.abs(x2 - x1) * 0.25);
  const color = typeColor(l.type);
  const faded = a.mode === 2 || b.mode === 2 || a.mode === 4 || b.mode === 4;

  ctx.globalAlpha = faded ? 0.35 : 1;
  ctx.strokeStyle = color;
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(x1, y1);
  ctx.bezierCurveTo(x1 + dist, y1, x2 - dist, y2, x2, y2);
  ctx.stroke();

  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.arc((x1 + x2) / 2, (y1 + y2) / 2, 4, 0, Math.PI * 2);
  ctx.fill();
  ctx.globalAlpha = 1;
}

function drawNode(node) {
  const isSel = selection.has(node);
  ctx.save();

  if (node.mode === 2) ctx.globalAlpha = 0.4;          // muted / "never"
  const bypass = node.mode === 4;

  const w = nodeW(node);
  const h = nodeH(node);

  ctx.shadowColor = 'rgba(0,0,0,0.5)';
  ctx.shadowBlur = 6;
  ctx.shadowOffsetX = 2;
  ctx.shadowOffsetY = 2;

  if (!node.collapsed) {
    ctx.fillStyle = bypass ? '#FF00FF' : node.bgcolor;
    roundRectC(node.x, node.y, w, h, ROUND, [false, false, true, true]);
    ctx.fill();
  }

  ctx.fillStyle = bypass ? '#A0A' : node.color;
  roundRectC(node.x, node.y - TITLE_H, w, TITLE_H, ROUND,
    node.collapsed ? [true, true, true, true] : [true, true, false, false]);
  ctx.fill();
  ctx.shadowColor = 'transparent';
  ctx.shadowBlur = 0;
  ctx.shadowOffsetX = 0;
  ctx.shadowOffsetY = 0;

  // outline around title + body
  ctx.strokeStyle = C.border;
  ctx.lineWidth = 1;
  roundRect(node.x - 0.5, node.y - TITLE_H - 0.5, w + 1, h + TITLE_H + 1, ROUND);
  ctx.stroke();

  if (settings.highlight && node.packColor) {      // stock nodes stay unmarked
    const hc = node.packColor;
    ctx.save();
    ctx.strokeStyle = hc;
    ctx.lineWidth = 2;
    ctx.shadowColor = hc;
    ctx.shadowBlur = 14;
    roundRect(node.x - 1, node.y - TITLE_H - 1, w + 2, h + TITLE_H + 2, ROUND);
    ctx.stroke();
    ctx.stroke();          // twice, so the glow reads at low zoom
    ctx.restore();
  }

  // title box + text
  ctx.fillStyle = node.raw.boxcolor || C.boxColor;
  roundRect(node.x + 8, node.y - TITLE_H + 10, 10, 10, 2);
  ctx.fill();

  ctx.fillStyle = isSel ? C.selected : C.titleText;
  ctx.font = '14px Arial';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  ctx.fillText(ellipsize(node.title, w - 34), node.x + 24, node.y - TITLE_H / 2 + 1);

  if (node.collapsed) {
    drawCollapsedSlots(node, w);
    ctx.restore();
    return;
  }

  ctx.save();
  roundRectC(node.x, node.y, w, h, ROUND, [false, false, true, true]);
  ctx.clip();

  drawSlots(node);
  drawWidgets(node);

  ctx.restore();

  // resize grip, bottom-right (LiteGraph draws the same triangle)
  ctx.fillStyle = 'rgba(255,255,255,0.25)';
  ctx.beginPath();
  ctx.moveTo(node.x + w - 1, node.y + h - 13);
  ctx.lineTo(node.x + w - 1, node.y + h - 1);
  ctx.lineTo(node.x + w - 13, node.y + h - 1);
  ctx.closePath();
  ctx.fill();

  ctx.restore();
}

/* A thick white ring set well clear of the pack glow, drawn in its own pass so
 * no neighbouring node can paint over it. */
function drawSelectionRing(node) {
  if (!selection.has(node)) return;
  const w = nodeW(node);
  const h = nodeH(node);
  const gap = Math.max(5, 7 / view.scale);          // clears the glow
  const lw = Math.max(2.5, 3.5 / view.scale);       // ~3.5 screen px at any zoom

  ctx.save();
  roundRect(node.x - gap, node.y - TITLE_H - gap, w + gap * 2, h + TITLE_H + gap * 2, ROUND + gap);

  ctx.strokeStyle = 'rgba(0,0,0,0.75)';             // dark backing, so the white
  ctx.lineWidth = lw + Math.max(2, 3 / view.scale); // reads over any background
  ctx.stroke();

  ctx.strokeStyle = C.selected;
  ctx.lineWidth = lw;
  ctx.stroke();
  ctx.restore();
}

/* A small tag sitting just outside the top-right corner, naming the pack the
 * node needs. Stock nodes get none. */
function drawPackLabel(node) {
  if (!node.packColor || !node.packName) return;
  const w = nodeW(node);
  ctx.font = '11px Arial';
  const text = ellipsize(node.packName, Math.max(90, w));
  const tw = ctx.measureText(text).width;
  const bw = tw + 12;
  const bh = 16;
  const bx = node.x + w - bw;
  const by = node.y - TITLE_H - bh - 3;

  ctx.save();
  ctx.fillStyle = 'rgba(20,20,20,0.92)';
  roundRect(bx, by, bw, bh, 4);
  ctx.fill();
  ctx.strokeStyle = node.packColor;
  ctx.lineWidth = 1;
  ctx.stroke();

  ctx.fillStyle = node.packColor;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(text, bx + bw / 2, by + bh / 2 + 0.5);
  ctx.restore();
}

function drawCollapsedSlots(node, w) {
  const y = node.y - TITLE_H / 2;
  if (node.inputs.length) {
    ctx.fillStyle = typeColor(node.inputs[0].type);
    ctx.beginPath(); ctx.arc(node.x, y, 4, 0, Math.PI * 2); ctx.fill();
  }
  if (node.outputs.length) {
    ctx.fillStyle = typeColor(node.outputs[0].type);
    ctx.beginPath(); ctx.arc(node.x + w, y, 4, 0, Math.PI * 2); ctx.fill();
  }
}

function drawSlots(node) {
  ctx.font = '12px Arial';
  ctx.textBaseline = 'middle';

  node.inputs.forEach((s, i) => {
    const [x, y] = slotPos(node, true, i);
    ctx.fillStyle = typeColor(s.type);
    ctx.beginPath();
    if (s.shape === 1) ctx.rect(x - 4, y - 4, 8, 8); else ctx.arc(x, y, 4, 0, Math.PI * 2);
    ctx.fill();
    if (s.link === null || s.link === undefined) {
      ctx.fillStyle = node.bgcolor;
      ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill();
    }
    ctx.fillStyle = C.text;
    ctx.textAlign = 'left';
    ctx.fillText(ellipsize(String(s.name ?? s.type ?? ''), node.w * 0.5), x + 10, y);
  });

  node.outputs.forEach((s, i) => {
    const [x, y] = slotPos(node, false, i);
    ctx.fillStyle = typeColor(s.type);
    ctx.beginPath();
    if (s.shape === 1) ctx.rect(x - 4, y - 4, 8, 8); else ctx.arc(x, y, 4, 0, Math.PI * 2);
    ctx.fill();
    if (!s.links || !s.links.length) {
      ctx.fillStyle = node.bgcolor;
      ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill();
    }
    ctx.fillStyle = C.text;
    ctx.textAlign = 'right';
    ctx.fillText(ellipsize(String(s.name ?? s.type ?? ''), node.w * 0.5), x - 10, y);
  });
}

function drawWidgets(node) {
  if (!node.widgets.length) return;
  let y = node.y + widgetsStartY(node);
  const x = node.x + WIDGET_MARGIN;
  const w = node.w - WIDGET_MARGIN * 2;
  const bottom = node.y + node.h - 4;

  // Multiline text widgets grow to fill whatever space the node has left.
  const textCount = node.widgets.filter(r => r.kind === 'text').length;
  const fixed = node.widgets.filter(r => r.kind !== 'text').length * (WIDGET_H + 4);
  const textH = textCount ? Math.max(40, (bottom - y - fixed - textCount * 4) / textCount) : 0;

  // The stored node height is what ComfyUI itself laid out, so it is the
  // authority: a row that will not fit inside it is a row ComfyUI did not draw.
  for (const rw of node.widgets) {
    if (bottom - y < 16) break;
    if (rw.kind === 'text') {
      drawTextWidget(x, y, w, Math.min(textH, bottom - y), rw);
      y += textH + 4;
    } else {
      if (y + WIDGET_H > bottom + 1) break;
      drawRowWidget(x, y, w, WIDGET_H, rw);
      y += WIDGET_H + 4;
    }
  }
}

function drawRowWidget(x, y, w, h, rw) {
  ctx.fillStyle = C.widgetBg;
  roundRect(x, y, w, h, h * 0.5);
  ctx.fill();
  ctx.strokeStyle = C.widgetOutline;
  ctx.lineWidth = 1;
  ctx.stroke();

  ctx.font = '12px Arial';
  ctx.textBaseline = 'middle';
  const cy = y + h * 0.5;

  const arrows = rw.kind === 'number' || rw.kind === 'combo';
  if (arrows) {
    ctx.fillStyle = C.widgetText2;
    ctx.textAlign = 'center';
    ctx.fillText('◀', x + 12, cy);
    ctx.fillText('▶', x + w - 12, cy);
  }

  const pad = arrows ? 22 : 10;
  let value = rw.kind === 'number' ? fmtNumber(rw.value) : String(rw.value);
  if (rw.kind === 'toggle') value = rw.value ? 'true' : 'false';

  let nameW = 0;
  if (rw.name) {
    ctx.fillStyle = C.widgetText2;
    ctx.textAlign = 'left';
    nameW = Math.min(ctx.measureText(rw.name).width, w * 0.55);
    ctx.fillText(ellipsize(rw.name, w * 0.55), x + pad, cy);
  }
  // Values always sit on the right, named or not. ComfyUI never centres them.
  ctx.fillStyle = C.widgetText;
  ctx.textAlign = 'right';
  ctx.fillText(ellipsize(value, w - pad * 2 - (nameW ? nameW + 8 : 0)), x + w - pad, cy);
}

function drawTextWidget(x, y, w, h, rw) {
  if (h <= 6) return;
  ctx.fillStyle = C.widgetBg;
  roundRect(x, y, w, h, 4);
  ctx.fill();
  ctx.strokeStyle = '#4a4a4a';
  ctx.lineWidth = 1;
  ctx.stroke();

  ctx.save();
  ctx.beginPath();
  ctx.rect(x + 4, y + 2, w - 8, h - 4);
  ctx.clip();

  ctx.font = '12px Arial';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'top';
  ctx.fillStyle = C.widgetText;

  const lines = wrap(String(rw.value), w - 12);
  let ty = y + 5;
  for (const line of lines) {
    if (ty > y + h - 12) break;
    ctx.fillText(line, x + 6, ty);
    ty += 15;
  }
  ctx.restore();
}

const wrapCache = new Map();
function wrap(text, maxW) {
  const key = maxW + '|' + text;
  const hit = wrapCache.get(key);
  if (hit) return hit;
  const out = [];
  for (const para of text.split('\n')) {
    if (!para) { out.push(''); continue; }
    let line = '';
    for (const word of para.split(' ')) {
      const test = line ? line + ' ' + word : word;
      if (ctx.measureText(test).width > maxW && line) { out.push(line); line = word; }
      else line = test;
    }
    out.push(line);
    if (out.length > 200) break;
  }
  if (wrapCache.size > 400) wrapCache.clear();
  wrapCache.set(key, out);
  return out;
}

/* ------------------------------------------------------------- hit testing */

function toGraph(cx, cy) {
  return [(cx - view.x) / view.scale, (cy - view.y) / view.scale];
}

// Outer rect of a node, title bar included.
function nodeRect(n) {
  return [n.x, n.y - TITLE_H, nodeW(n), nodeH(n) + TITLE_H];
}

function nodeAt(gx, gy) {
  for (let i = order.length - 1; i >= 0; i--) {
    const n = nodes[order[i]];
    const [x, y, w, h] = nodeRect(n);
    if (gx >= x && gx <= x + w && gy >= y && gy <= y + h) return n;
  }
  return null;
}

/* Which edge/corner of a rect the point is on, or null. Returns one of
 * nw n ne e se s sw w. */
function handleAt(rect, gx, gy, want, out) {
  const [x, y, w, h] = rect;
  // never let the grab zone swallow the whole thing at low zoom
  const tol = Math.min(want, w * 0.25, h * 0.25);
  // the zone reaches barely outside the border, just enough to absorb pointer
  // rounding, not enough to steal clicks aimed at a neighbour
  if (gx < x - out || gx > x + w + out || gy < y - out || gy > y + h + out) return null;
  const left = Math.abs(gx - x) <= tol;
  const right = Math.abs(gx - (x + w)) <= tol;
  const top = Math.abs(gy - y) <= tol;
  const bottom = Math.abs(gy - (y + h)) <= tol;
  if (top && left) return 'nw';
  if (top && right) return 'ne';
  if (bottom && left) return 'sw';
  if (bottom && right) return 'se';
  if (left) return 'w';
  if (right) return 'e';
  if (top) return 'n';
  if (bottom) return 's';
  return null;
}

const CURSORS = {
  nw: 'nwse-resize', se: 'nwse-resize',
  ne: 'nesw-resize', sw: 'nesw-resize',
  n: 'ns-resize', s: 'ns-resize',
  e: 'ew-resize', w: 'ew-resize',
};

/* What is under the pointer: a node resize handle, a node, a group handle,
 * a group title, or nothing. */
function probe(gx, gy) {
  const tol = HANDLE / view.scale;
  const out = 2 / view.scale;

  for (let i = order.length - 1; i >= 0; i--) {
    const n = nodes[order[i]];
    // the collapse dot wins over the resize edge it sits near
    if (inTitleBox(n, gx, gy)) return { kind: 'node', node: n };
    if (!n.collapsed) {
      const hnd = handleAt(nodeRect(n), gx, gy, tol, out);
      // the top edge is the title bar; dragging it should move, not resize
      if (hnd && hnd !== 'n') return { kind: 'node-resize', node: n, handle: hnd };
    }
    const [x, y, w, h] = nodeRect(n);
    if (gx >= x && gx <= x + w && gy >= y && gy <= y + h) return { kind: 'node', node: n };
  }

  for (let i = groups.length - 1; i >= 0; i--) {
    const g = groups[i];
    const [x, y, w] = g.b;
    const inTitle = gx >= x && gx <= x + w && gy >= y && gy <= y + g.font + 10;
    const hnd = handleAt(g.b, gx, gy, tol, out);
    // the title bar drags the box; only its corners still resize, so the top
    // edge handle never swallows the whole strip
    if (hnd && !(inTitle && hnd === 'n')) return { kind: 'group-resize', group: g, handle: hnd };
    if (inTitle) return { kind: 'group', group: g };
  }
  return { kind: 'canvas' };
}

function nodesInGroup(g) {
  const [x, y, w, h] = g.b;
  return nodes.filter(n => {
    const cx = n.x + nodeW(n) / 2, cy = n.y + nodeH(n) / 2;
    return cx >= x && cx <= x + w && cy >= y && cy <= y + h;
  });
}

/* --------------------------------------------------------------- interaction */

let drag = null;

function bringToFront(node) {
  const idx = nodes.indexOf(node);
  const at = order.indexOf(idx);
  if (at >= 0) order.splice(at, 1);
  order.push(idx);
}

canvas.addEventListener('contextmenu', e => e.preventDefault());

// The title dot, which toggles collapse on click (as in ComfyUI).
function inTitleBox(n, gx, gy) {
  return gx >= n.x + 6 && gx <= n.x + 20 && gy >= n.y - TITLE_H + 8 && gy <= n.y - TITLE_H + 22;
}

canvas.addEventListener('pointerdown', e => {
  stopRename(true);
  closeMenu();
  canvas.setPointerCapture(e.pointerId);
  const [gx, gy] = toGraph(e.offsetX, e.offsetY);

  // right / middle button, or space-less shift-drag: pan
  if (e.button === 1 || e.button === 2) {
    drag = { mode: 'pan', sx: e.offsetX, sy: e.offsetY, vx: view.x, vy: view.y, menu: e.button === 2 };
    canvas.style.cursor = 'grabbing';
    return;
  }
  if (e.button !== 0 || !nodes.length) return;

  const hit = probe(gx, gy);

  if (hit.kind === 'node-resize') {
    bringToFront(hit.node);
    drag = {
      mode: 'resize-node', node: hit.node, handle: hit.handle, gx, gy,
      start: { x: hit.node.x, y: hit.node.y, w: hit.node.w, h: hit.node.h },
    };
    return;
  }

  if (hit.kind === 'node') {
    const node = hit.node;
    selectedGroup = null;
    if (inTitleBox(node, gx, gy)) {
      node.collapsed = !node.collapsed;
      dirty = true;
      return;
    }
    if (e.altKey) {                       // alt only ever removes
      selection.delete(node);
      dirty = true;
      return;
    }
    // shift or ctrl toggles this node in or out of the selection
    if (e.shiftKey || e.ctrlKey || e.metaKey) {
      if (selection.has(node)) selection.delete(node); else selection.add(node);
    } else if (!selection.has(node)) {
      selection = new Set([node]);
    }
    bringToFront(node);
    const movers = selection.has(node) ? [...selection] : [node];
    drag = { mode: 'move', movers: movers.map(n => ({ n, dx: gx - n.x, dy: gy - n.y })) };
    canvas.style.cursor = 'move';
    dirty = true;
    return;
  }

  if (hit.kind === 'group-resize') {
    selectedGroup = hit.group;
    dirty = true;
    drag = { mode: 'resize-group', group: hit.group, handle: hit.handle, start: hit.group.b.slice() };
    return;
  }

  if (hit.kind === 'group') {
    const g = hit.group;
    selectedGroup = g;
    dirty = true;
    drag = {
      mode: 'move-group', group: g, ox: gx - g.b[0], oy: gy - g.b[1],
      // shift moves the box alone and leaves its contents where they are
      members: e.shiftKey ? [] : nodesInGroup(g).map(n => ({ n, dx: n.x - g.b[0], dy: n.y - g.b[1] })),
    };
    canvas.style.cursor = 'move';
    return;
  }

  // empty canvas: rubber-band select. Shift adds, ctrl inverts and alt
  // subtracts. All three keep whatever is already selected.
  selectedGroup = null;
  const sub = e.altKey;
  const add = e.shiftKey && !sub;
  const invert = (e.ctrlKey || e.metaKey) && !sub;
  if (!add && !invert && !sub) selection = new Set();
  drag = { mode: 'marquee', add, invert, sub, base: new Set(selection) };
  marquee = { x0: gx, y0: gy, x1: gx, y1: gy };
  dirty = true;
});

canvas.addEventListener('pointermove', e => {
  const [gx, gy] = toGraph(e.offsetX, e.offsetY);

  if (!drag) {
    if (!nodes.length) { canvas.style.cursor = 'default'; return; }
    const hit = probe(gx, gy);
    canvas.style.cursor =
      hit.kind === 'node-resize' || hit.kind === 'group-resize' ? CURSORS[hit.handle] :
      hit.kind === 'node' || hit.kind === 'group' ? 'move' : 'default';
    return;
  }

  switch (drag.mode) {
    case 'pan':
      view.x = drag.vx + (e.offsetX - drag.sx);
      view.y = drag.vy + (e.offsetY - drag.sy);
      break;

    case 'move':
      for (const m of drag.movers) {
        m.n.x = Math.round(gx - m.dx);
        m.n.y = Math.round(gy - m.dy);
      }
      break;

    case 'move-group': {
      const g = drag.group;
      g.b[0] = Math.round(gx - drag.ox);
      g.b[1] = Math.round(gy - drag.oy);
      for (const m of drag.members) {
        m.n.x = g.b[0] + m.dx;
        m.n.y = g.b[1] + m.dy;
      }
      break;
    }

    case 'resize-node': {
      const n = drag.node;
      const s = drag.start;
      const dx = gx - drag.gx, dy = gy - drag.gy;
      if (drag.handle.includes('e')) n.w = Math.max(n.minW, Math.round(s.w + dx));
      if (drag.handle.includes('s')) n.h = Math.max(n.minH, Math.round(s.h + dy));
      if (drag.handle.includes('w')) {
        const right = s.x + s.w;
        n.x = Math.round(Math.min(s.x + dx, right - n.minW));
        n.w = right - n.x;
      }
      if (drag.handle.includes('n')) {
        const bottom = s.y + s.h;
        n.y = Math.round(Math.min(s.y + dy, bottom - n.minH));
        n.h = bottom - n.y;
      }
      break;
    }

    case 'resize-group': {
      const b = drag.group.b;
      const s = drag.start;
      if (drag.handle.includes('e')) b[2] = Math.max(GROUP_MIN_W, Math.round(gx - s[0]));
      if (drag.handle.includes('s')) b[3] = Math.max(GROUP_MIN_H, Math.round(gy - s[1]));
      if (drag.handle.includes('w')) {
        const right = s[0] + s[2];
        b[0] = Math.round(Math.min(gx, right - GROUP_MIN_W));
        b[2] = right - b[0];
      }
      if (drag.handle.includes('n')) {
        const bottom = s[1] + s[3];
        b[1] = Math.round(Math.min(gy, bottom - GROUP_MIN_H));
        b[3] = bottom - b[1];
      }
      break;
    }

    case 'marquee': {
      marquee.x1 = gx;
      marquee.y1 = gy;
      const x0 = Math.min(marquee.x0, marquee.x1), x1 = Math.max(marquee.x0, marquee.x1);
      const y0 = Math.min(marquee.y0, marquee.y1), y1 = Math.max(marquee.y0, marquee.y1);
      selection = new Set(drag.add || drag.invert || drag.sub ? drag.base : []);
      for (const n of nodes) {
        const [nx, ny, nw, nh] = nodeRect(n);
        if (!(nx < x1 && nx + nw > x0 && ny < y1 && ny + nh > y0)) continue;
        if (drag.sub || (drag.invert && drag.base.has(n))) selection.delete(n);
        else selection.add(n);
      }
      break;
    }
  }
  dirty = true;
});

function endDrag() {
  if (drag && drag.mode === 'marquee') marquee = null;
  drag = null;
  canvas.style.cursor = 'default';
  dirty = true;
}

canvas.addEventListener('pointerup', e => {
  // a right-click that did not pan opens the menu instead
  if (drag && drag.mode === 'pan' && drag.menu &&
      Math.abs(e.offsetX - drag.sx) < 4 && Math.abs(e.offsetY - drag.sy) < 4) {
    endDrag();
    openMenu(e.offsetX, e.offsetY);
    return;
  }
  endDrag();
});
canvas.addEventListener('pointercancel', endDrag);

/* ------------------------------------------------------------------ colors */

// LiteGraph's own node palette, plus the group tint ComfyUI pairs with each.
const NODE_COLORS = [
  ['red', '#322', '#533', '#A88'],
  ['brown', '#332922', '#593930', '#b06634'],
  ['green', '#232', '#353', '#8A8'],
  ['blue', '#223', '#335', '#88A'],
  ['pale blue', '#2a363b', '#3f5159', '#3f5159'],
  ['cyan', '#233', '#355', '#8AA'],
  ['purple', '#323', '#535', '#a1309b'],
  ['yellow', '#432', '#653', '#b58b2a'],
  ['black', '#222', '#000', '#444'],
];

function darken(hex, f) {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map(c => c + c).join('');
  const n = parseInt(h, 16);
  const c = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(v => Math.round(v * f));
  return '#' + c.map(v => v.toString(16).padStart(2, '0')).join('');
}

function recolorNodes(list, title, body) {
  for (const n of list) {
    if (!title) {
      delete n.raw.color; delete n.raw.bgcolor;
      n.color = C.nodeColor; n.bgcolor = C.nodeBg;
    } else {
      n.raw.color = title; n.raw.bgcolor = body;
      n.color = title; n.bgcolor = body;
    }
  }
  dirty = true;
}

function recolorGroup(g, color) {
  g.color = color || '#3f789e';
  g.raw.color = g.color;
  dirty = true;
}

/* ------------------------------------------------------------- context menu */

let menuEls = [];

function closeMenu(depth = 0) {
  while (menuEls.length > depth) menuEls.pop().remove();
}

/* Items: {label, fn, cls, children} | {header} | {swatches} | {custom} */
function buildMenu(items, sx, sy, depth) {
  closeMenu(depth);
  const el = document.createElement('div');
  el.className = 'ctxmenu';

  for (const it of items) {
    if (it.node) { el.appendChild(it.node); continue; }
    const b = document.createElement('button');
    const lab = document.createElement('span');
    lab.textContent = it.label;
    b.appendChild(lab);
    if (it.children) {
      const arrow = document.createElement('span');
      arrow.className = 'arrow';
      arrow.textContent = '▸';
      b.appendChild(arrow);
    }
    if (it.cls) b.className = it.cls;
    b.onclick = () => {
      if (it.children) {
        const r = b.getBoundingClientRect();
        buildMenu(it.children(), r.right + 2, r.top - 5, depth + 1);
      } else {
        closeMenu();
        it.fn();
      }
    };
    el.appendChild(b);
  }

  document.body.appendChild(el);
  menuEls.push(el);
  const r = el.getBoundingClientRect();
  el.style.left = Math.max(4, Math.min(sx, innerWidth - r.width - 8)) + 'px';
  el.style.top = Math.max(4, Math.min(sy, innerHeight - r.height - 8)) + 'px';
  return el;
}

function swatchRow(colors, onPick) {
  const wrap = document.createElement('div');
  wrap.className = 'swatches';
  for (const [name, title, body, group] of colors) {
    const b = document.createElement('button');
    b.title = name;
    b.style.background = group ? `linear-gradient(${title} 0 40%, ${body} 40% 100%)` : title;
    b.onclick = () => { closeMenu(); onPick(title, body, group); };
    wrap.appendChild(b);
  }
  return wrap;
}

function customRow(initial, onPick) {
  const l = document.createElement('label');
  l.className = 'custom';
  l.textContent = 'Custom…';
  const inp = document.createElement('input');
  inp.type = 'color';
  inp.value = initial;
  inp.oninput = () => onPick(inp.value);
  inp.onchange = () => { onPick(inp.value); closeMenu(); };
  l.appendChild(inp);
  return l;
}

function colorMenuForNodes(list) {
  return () => [
    { node: swatchRow(NODE_COLORS, (title, body) => recolorNodes(list, title, body)) },
    { node: customRow(list[0].bgcolor || C.nodeBg, v => recolorNodes(list, darken(v, 0.55), v)) },
    { label: 'Default', fn: () => recolorNodes(list, null) },
  ];
}

function colorMenuForGroup(g) {
  return () => [
    { node: swatchRow(NODE_COLORS.map(c => [c[0], c[3], c[3], true]), t => recolorGroup(g, t)) },
    { node: customRow(g.color, v => recolorGroup(g, v)) },
    { label: 'Default', fn: () => recolorGroup(g, null) },
  ];
}

function packHeader(n) {
  const d = document.createElement('div');
  d.className = 'mhead';
  const k = document.createElement('div');
  k.className = 'k';
  d.appendChild(k);

  const pack = n.packKey && n.packKey !== '?' && report
    ? report.packs.find(p => p.key === n.packKey) : null;

  if (pack) {
    k.textContent = 'From node pack';
    const v = document.createElement('div');
    v.className = 'v';
    v.textContent = pack.title;
    d.appendChild(v);
    const row = document.createElement('div');
    row.className = 'row';
    const a = document.createElement('a');
    a.href = pack.url;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = pack.url;
    const copy = document.createElement('button');
    copy.textContent = 'Copy';
    copy.onclick = e => { e.preventDefault(); closeMenu(); copyText(pack.url, 'URL'); };
    row.append(a, copy);
    d.appendChild(row);
  } else if (n.packKey === '?') {
    k.textContent = 'Unrecognised node: not in the ComfyUI-Manager registry';
  } else {
    k.textContent = 'Stock ComfyUI node';
  }
  return d;
}

function openMenu(sx, sy) {
  closeMenu();
  if (!nodes.length) return;
  const [gx, gy] = toGraph(sx, sy);
  const hit = probe(gx, gy);
  const items = [];

  if (hit.kind === 'group' || hit.kind === 'group-resize') {
    const g = hit.group;
    selectedGroup = g;
    dirty = true;
    items.push({ label: 'Rename…', fn: () => startRename({ kind: 'group', obj: g }) });
    items.push({ label: 'Color', children: colorMenuForGroup(g) });
    items.push({ label: 'Fit to contents', fn: () => {
      if (!fitGroupTo(g, nodesInGroup(g))) toast('That box has no nodes in it', true);
    } });
    items.push({ label: 'Select its nodes', fn: () => { selection = new Set(nodesInGroup(g)); dirty = true; } });
    items.push({ label: 'Delete comment box', cls: 'danger', fn: () => deleteGroup(g) });
  } else if (hit.kind === 'node' || hit.kind === 'node-resize') {
    const n = hit.node;
    const many = selection.size > 1 && selection.has(n);
    const targets = many ? [...selection] : [n];

    items.push({ node: packHeader(n) });
    items.push({ label: 'Rename…', fn: () => startRename({ kind: 'node', obj: n }) });
    items.push({
      label: 'Color',
      children: colorMenuForNodes(targets),
    });
    items.push({ label: n.collapsed ? 'Expand' : 'Collapse', fn: () => { n.collapsed = !n.collapsed; dirty = true; } });
    items.push({
      label: `Select all ${n.type} nodes`,
      fn: () => {
        selection = new Set(nodes.filter(o => o.type === n.type));
        dirty = true;
        toast(`Selected every ${n.type}`);
      },
    });
    if (many) items.push({ label: 'Group selected nodes', fn: groupSelection });
  } else {
    if (selection.size) items.push({ label: 'Group selected nodes', fn: groupSelection });
    items.push({ label: 'Select all', fn: () => { selection = new Set(nodes); dirty = true; } });
    if (selection.size) items.push({ label: 'Clear selection', fn: () => { selection = new Set(); dirty = true; } });
    items.push({ label: 'Fit view', fn: fit });
  }

  buildMenu(items, sx, sy, 0);
}

canvas.addEventListener('wheel', e => {
  e.preventDefault();
  stopRename(true);
  closeMenu();
  const factor = e.deltaY < 0 ? 1.1 : 1 / 1.1;
  const ns = Math.min(4, Math.max(0.05, view.scale * factor));
  const k = ns / view.scale;
  view.x = e.offsetX - (e.offsetX - view.x) * k;
  view.y = e.offsetY - (e.offsetY - view.y) * k;
  view.scale = ns;
  dirty = true;
}, { passive: false });

/* Double-click a title to rename it: node titles and comment box titles both. */
canvas.addEventListener('dblclick', e => {
  const [gx, gy] = toGraph(e.offsetX, e.offsetY);
  const hit = probe(gx, gy);
  if ((hit.kind === 'node' || hit.kind === 'node-resize') && gy <= hit.node.y && !inTitleBox(hit.node, gx, gy)) {
    startRename({ kind: 'node', obj: hit.node });
  } else if (hit.kind === 'group' || hit.kind === 'group-resize') {
    const g = hit.group;
    if (gy <= g.b[1] + g.font + 8) startRename({ kind: 'group', obj: g });
  }
});

/* ------------------------------------------------------- groups & renaming */

// ComfyUI's own group color choices, cycled as boxes are added.
const GROUP_COLORS = ['#3f789e', '#a1309b', '#88A', '#3f5159', '#653', '#354', '#535', '#8A8'];

const GROUP_PAD = 26;          // breathing room around the nodes inside
const LABEL_SPACE = 22;        // the pack tag that floats above each node

/* Size a box so it comfortably contains the given nodes. */
function fitGroupTo(g, list) {
  if (!list.length) return false;
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const n of list) {
    const [x, y, w, h] = nodeRect(n);
    minX = Math.min(minX, x); minY = Math.min(minY, y - LABEL_SPACE);
    maxX = Math.max(maxX, x + w); maxY = Math.max(maxY, y + h);
  }
  const titleSpace = g.font + 12;
  g.b[0] = Math.round(minX - GROUP_PAD);
  g.b[1] = Math.round(minY - GROUP_PAD - titleSpace);
  g.b[2] = Math.round(maxX - minX + GROUP_PAD * 2);
  g.b[3] = Math.round(maxY - minY + GROUP_PAD * 2 + titleSpace);
  dirty = true;
  return true;
}

/* Wrap the selected nodes in a new comment box. */
function groupSelection() {
  if (!raw) { toast('Nothing loaded', true); return; }
  if (!selection.size) { toast('Select some nodes first', true); return; }

  const rawGroup = {
    title: 'Group',
    bounding: [0, 0, 100, 100],
    color: GROUP_COLORS[groups.length % GROUP_COLORS.length],
    font_size: 24,
    locked: false,
  };
  if (!Array.isArray(raw.groups)) raw.groups = [];
  raw.groups.push(rawGroup);

  const g = { raw: rawGroup, title: rawGroup.title, b: rawGroup.bounding.slice(), color: rawGroup.color, font: 24 };
  fitGroupTo(g, [...selection]);
  groups.push(g);
  selectedGroup = g;
  dirty = true;
  startRename({ kind: 'group', obj: g });
}

function deleteGroup(g) {
  const i = groups.indexOf(g);
  if (i < 0) return;
  groups.splice(i, 1);
  if (raw && Array.isArray(raw.groups)) {
    const j = raw.groups.indexOf(g.raw);
    if (j >= 0) raw.groups.splice(j, 1);
  }
  if (selectedGroup === g) selectedGroup = null;
  dirty = true;
  toast('Comment box deleted');
}

let editor = null;

function stopRename(commit) {
  if (!editor) return;
  const { input, target } = editor;
  editor = null;                       // before removal, so blur does not recurse
  if (commit) {
    const value = input.value.trim();
    if (target.kind === 'node') {
      const n = target.obj;
      n.title = value || n.type;
      if (value && value !== n.type) n.raw.title = value; else delete n.raw.title;
    } else {
      target.obj.title = value;
      target.obj.raw.title = value;
    }
  }
  input.remove();
  dirty = true;
}

/* An input floated over the title being edited. */
function startRename(target) {
  stopRename(true);

  let gx, gy, gw, fontPx;
  if (target.kind === 'node') {
    const n = target.obj;
    gx = n.x + 22; gy = n.y - TITLE_H; gw = nodeW(n) - 26; fontPx = 14;
  } else {
    const g = target.obj;
    gx = g.b[0] + 4; gy = g.b[1] + 2; gw = g.b[2] - 8; fontPx = g.font;
  }

  const input = document.createElement('input');
  input.className = 'rename';
  input.value = target.kind === 'node' ? target.obj.title : target.obj.title;
  input.style.left = (view.x + gx * view.scale) + 'px';
  input.style.top = (view.y + gy * view.scale) + 'px';
  input.style.width = Math.max(80, gw * view.scale) + 'px';
  input.style.height = Math.max(22, (target.kind === 'node' ? TITLE_H : fontPx + 6) * view.scale) + 'px';
  input.style.fontSize = Math.max(12, fontPx * view.scale) + 'px';
  document.body.appendChild(input);
  input.focus();
  input.select();

  input.addEventListener('keydown', e => {
    e.stopPropagation();
    if (e.key === 'Enter') stopRename(true);
    else if (e.key === 'Escape') stopRename(false);
  });
  input.addEventListener('blur', () => stopRename(true));

  editor = { input, target };
}

/* ---------------------------------------------------------------- alignment */

function selected() {
  return [...selection];
}

function needSelection(min) {
  if (selection.size < min) {
    toast(min > 1 ? 'Select two or more nodes first' : 'Select a node first', true);
    return false;
  }
  return true;
}

function arrange(act) {
  const gap = Math.max(0, parseInt(document.getElementById('gap').value, 10) || 0);
  if (!needSelection(2)) return;
  const sel = selected();

  const top = n => n.y - TITLE_H;
  const height = n => nodeH(n) + TITLE_H;

  switch (act) {
    case 'left': {
      const x = Math.min(...sel.map(n => n.x));
      sel.forEach(n => { n.x = x; });
      break;
    }
    case 'right': {
      const r = Math.max(...sel.map(n => n.x + nodeW(n)));
      sel.forEach(n => { n.x = r - nodeW(n); });
      break;
    }
    case 'centerx': {
      const c = sel.reduce((a, n) => a + n.x + nodeW(n) / 2, 0) / sel.length;
      sel.forEach(n => { n.x = Math.round(c - nodeW(n) / 2); });
      break;
    }
    case 'top': {
      const y = Math.min(...sel.map(top));
      sel.forEach(n => { n.y = y + TITLE_H; });
      break;
    }
    case 'bottom': {
      const b = Math.max(...sel.map(n => top(n) + height(n)));
      sel.forEach(n => { n.y = b - height(n) + TITLE_H; });
      break;
    }
    case 'middley': {
      const c = sel.reduce((a, n) => a + top(n) + height(n) / 2, 0) / sel.length;
      sel.forEach(n => { n.y = Math.round(c - height(n) / 2) + TITLE_H; });
      break;
    }
    case 'disth': {
      const s = sel.slice().sort((a, b) => a.x - b.x);
      const first = s[0], last = s[s.length - 1];
      const span = (last.x + nodeW(last)) - first.x;
      const used = s.reduce((a, n) => a + nodeW(n), 0);
      const g = (span - used) / (s.length - 1);
      let x = first.x;
      for (const n of s) { n.x = Math.round(x); x += nodeW(n) + g; }
      break;
    }
    case 'distv': {
      const s = sel.slice().sort((a, b) => top(a) - top(b));
      const first = s[0], last = s[s.length - 1];
      const span = (top(last) + height(last)) - top(first);
      const used = s.reduce((a, n) => a + height(n), 0);
      const g = (span - used) / (s.length - 1);
      let y = top(first);
      for (const n of s) { n.y = Math.round(y) + TITLE_H; y += height(n) + g; }
      break;
    }
    case 'stackv': {
      const s = sel.slice().sort((a, b) => top(a) - top(b));
      const x = Math.min(...s.map(n => n.x));
      let y = top(s[0]);
      for (const n of s) {
        n.x = x;
        n.y = Math.round(y) + TITLE_H;
        y += height(n) + gap;
      }
      break;
    }
    case 'matchw': case 'matchh': {
      // the topmost node is the reference, so a column matches its header
      const ref = sel.reduce((a, n) => (top(n) < top(a) ? n : a), sel[0]);
      for (const n of sel) {
        if (act === 'matchw') n.w = Math.max(n.minW, ref.w);
        else n.h = Math.max(n.minH, ref.h);
      }
      break;
    }
    case 'stackh': {
      const s = sel.slice().sort((a, b) => a.x - b.x);
      const y = Math.min(...s.map(top)) + TITLE_H;
      let x = s[0].x;
      for (const n of s) {
        n.y = y;
        n.x = Math.round(x);
        x += nodeW(n) + gap;
      }
      break;
    }
  }
  dirty = true;
}

/* ------------------------------------------------------------------ viewport */

function bounds() {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  const push = (x, y, w, h) => {
    minX = Math.min(minX, x); minY = Math.min(minY, y);
    maxX = Math.max(maxX, x + w); maxY = Math.max(maxY, y + h);
  };
  for (const n of nodes) push(...nodeRect(n));
  for (const g of groups) push(g.b[0], g.b[1], g.b[2], g.b[3]);
  if (!isFinite(minX)) return null;
  return { minX, minY, maxX, maxY };
}

function fit() {
  const b = bounds();
  if (!b) return;
  const pad = 60;
  const sw = innerWidth - pad * 2, sh = innerHeight - pad * 2;
  const scale = Math.min(sw / (b.maxX - b.minX), sh / (b.maxY - b.minY), 1.5);
  view.scale = Math.max(0.02, scale);
  view.x = pad + (sw - (b.maxX - b.minX) * view.scale) / 2 - b.minX * view.scale;
  view.y = pad + (sh - (b.maxY - b.minY) * view.scale) / 2 - b.minY * view.scale;
  dirty = true;
}

/* ------------------------------------------------------------------- report */

function typeList(map) {
  return [...map.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([t, c]) => (c > 1 ? `${t} ×${c}` : t))
    .join(', ');
}

function renderReport() {
  const body = document.getElementById('report-body');
  if (!report) { body.innerHTML = '<div class="summary">No workflow loaded.</div>'; return; }

  const coreCount = report.core.reduce((a, e) => a + e[1], 0);
  const unknownCount = report.unknown.reduce((a, e) => a + e[1], 0);
  const html = [];

  html.push(`<div class="summary"><b>${report.packs.length}</b> custom node pack${report.packs.length === 1 ? '' : 's'}
    needed · <b>${coreCount}</b> stock node${coreCount === 1 ? '' : 's'}${unknownCount ? ` · <b>${unknownCount}</b> unrecognised` : ''}</div>`);

  for (const p of report.packs) {
    html.push(`<div class="pack">
      <div class="swatch" style="background:${p.color}"></div>
      <div class="body">
        <span class="count">${p.count}</span>
        <div class="name">${esc(p.title)}</div>
        <div class="url-row">
          <a class="url" href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.url)}</a>
          <button class="copy-url" data-url="${esc(p.url)}">Copy</button>
        </div>
        <div class="types">${esc(typeList(p.types))}</div>
        ${p.alt.size ? `<div class="warn">also provided by: ${esc([...p.alt].join(', '))}</div>` : ''}
      </div></div>`);
  }

  if (report.unknown.length) {
    html.push(`<div class="pack">
      <div class="swatch" style="background:${UNKNOWN_COLOR}"></div>
      <div class="body">
        <span class="count">${unknownCount}</span>
        <div class="name">Unrecognised nodes</div>
        <div class="types">${esc(report.unknown.map(([t, c]) => (c > 1 ? `${t} ×${c}` : t)).join(', '))}</div>
        <div class="warn">not in the ComfyUI-Manager registry: renamed, private, or a group node</div>
      </div></div>`);
  }

  if (report.core.length) {
    html.push(`<div class="pack">
      <div class="swatch" style="background:${CORE_COLOR}"></div>
      <div class="body">
        <span class="count">${coreCount}</span>
        <div class="name">Stock ComfyUI</div>
        <div class="types">${esc(report.core.map(([t, c]) => (c > 1 ? `${t} ×${c}` : t)).join(', '))}</div>
      </div></div>`);
  }

  body.innerHTML = html.join('');
}

function esc(s) {
  return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function reportText() {
  if (!report) return '';
  const lines = [`${fileName}: ${nodes.length} nodes`, ''];
  lines.push(`Custom node packs required (${report.packs.length}):`);
  for (const p of report.packs) lines.push(`  - ${p.title} (${p.count} nodes) ${p.url}`);
  if (report.unknown.length) {
    lines.push('', 'Unrecognised node types:');
    for (const [t, c] of report.unknown) lines.push(`  - ${t}${c > 1 ? ` ×${c}` : ''}`);
  }
  lines.push('', `Stock ComfyUI nodes: ${report.core.reduce((a, e) => a + e[1], 0)}`);
  return lines.join('\n');
}

function copyText(text, what) {
  navigator.clipboard.writeText(text).then(
    () => toast(what + ' copied'),
    () => toast('Clipboard blocked by the browser', true));
}

/* ------------------------------------------------------------------- saving */

function writeSize(n) {
  const s = n.raw.size;
  if (Array.isArray(s)) { s[0] = n.w; s[1] = n.h; }
  else if (s && typeof s === 'object') { s['0'] = n.w; s['1'] = n.h; }
  else n.raw.size = [n.w, n.h];
}

function save() {
  if (!raw) { toast('Nothing loaded', true); return; }
  for (const n of nodes) {
    if (Array.isArray(n.raw.pos)) { n.raw.pos[0] = n.x; n.raw.pos[1] = n.y; }
    else n.raw.pos = [n.x, n.y];
    writeSize(n);
    n.raw.flags = n.raw.flags || {};
    if (n.collapsed) n.raw.flags.collapsed = true; else delete n.raw.flags.collapsed;
  }
  for (const g of groups) g.raw.bounding = g.b.slice();

  const blob = new Blob([JSON.stringify(raw, null, 2)], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = fileName.replace(/\.(json|png|jpe?g|webp)$/i, '') + '.json';
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
  toast('Saved ' + a.download);
}

/* -------------------------------------------------------------- file loading */

/* ComfyUI embeds the graph in the images it saves, so those load like a .json:
 * PNG keeps it in a "workflow" text chunk, JPEG and WebP in EXIF. */

const utf8 = new TextDecoder();
const latin1 = new TextDecoder('latin1');

function pngChunks(d) {
  const out = [];
  const dv = new DataView(d.buffer, d.byteOffset, d.byteLength);
  let p = 8;
  while (p + 8 <= d.length) {
    const len = dv.getUint32(p);
    const type = latin1.decode(d.subarray(p + 4, p + 8));
    if (type === 'IEND') break;
    if (type === 'tEXt' || type === 'zTXt' || type === 'iTXt')
      out.push([type, d.subarray(p + 8, p + 8 + len)]);
    p += len + 12;
  }
  return out;
}

async function inflate(bytes) {
  const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'));
  return utf8.decode(await new Response(stream).arrayBuffer());
}

async function pngText(d) {
  const out = {};
  for (const [type, body] of pngChunks(d)) {
    const z = body.indexOf(0);
    if (z < 0) continue;
    const key = latin1.decode(body.subarray(0, z));
    try {
      if (type === 'tEXt') {
        out[key] = latin1.decode(body.subarray(z + 1));
      } else if (type === 'zTXt') {
        out[key] = await inflate(body.subarray(z + 2));
      } else {
        const compressed = body[z + 1];
        let q = body.indexOf(0, z + 3) + 1;   // past the language tag
        q = body.indexOf(0, q) + 1;           // past the translated keyword
        const rest = body.subarray(q);
        out[key] = compressed ? await inflate(rest) : utf8.decode(rest);
      }
    } catch (err) {
      /* one unreadable chunk should not sink the whole file */
    }
  }
  return out;
}

const EXIF_SIZES = { 1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 7: 1, 9: 4, 10: 8, 11: 4, 12: 8 };
const EXIF_TEXT_TAGS = new Set([0x010e, 0x010f, 0x9286]);   // description, make, user comment

function exifValue(b, tag) {
  if (tag === 0x9286 && b.length > 8) {
    const code = latin1.decode(b.subarray(0, 8));
    const body = b.subarray(8);
    if (code.startsWith('UNICODE'))
      return new TextDecoder(body[0] === 0 ? 'utf-16be' : 'utf-16le').decode(body);
    b = body;
  }
  return utf8.decode(b).replace(/\0+$/, '');
}

function exifStrings(d) {
  const out = [];
  if (!d || d.length < 8) return out;
  const le = d[0] === 0x49;
  const dv = new DataView(d.buffer, d.byteOffset, d.byteLength);
  const readIfd = (off, depth) => {
    if (off <= 0 || off + 2 > d.length || depth > 2) return;
    const n = dv.getUint16(off, le);
    for (let i = 0; i < n; i++) {
      const e = off + 2 + i * 12;
      if (e + 12 > d.length) return;
      const tag = dv.getUint16(e, le);
      if (tag === 0x8769) { readIfd(dv.getUint32(e + 8, le), depth + 1); continue; }
      if (!EXIF_TEXT_TAGS.has(tag)) continue;
      const bytes = dv.getUint32(e + 4, le) * (EXIF_SIZES[dv.getUint16(e + 2, le)] || 1);
      const at = bytes > 4 ? dv.getUint32(e + 8, le) : e + 8;
      if (at + bytes <= d.length) out.push(exifValue(d.subarray(at, at + bytes), tag));
    }
  };
  readIfd(dv.getUint32(4, le), 0);
  return out;
}

function jpegExif(d) {
  let p = 2;
  while (p + 4 <= d.length && d[p] === 0xff) {
    const marker = d[p + 1];
    if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd9)) { p += 2; continue; }
    if (marker === 0xda) break;                       // start of scan: no metadata past here
    const len = (d[p + 2] << 8) | d[p + 3];
    if (marker === 0xe1 && latin1.decode(d.subarray(p + 4, p + 10)) === 'Exif\0\0')
      return d.subarray(p + 10, p + 2 + len);
    p += 2 + len;
  }
  return null;
}

function webpExif(d) {
  const dv = new DataView(d.buffer, d.byteOffset, d.byteLength);
  let p = 12;
  while (p + 8 <= d.length) {
    const id = latin1.decode(d.subarray(p, p + 4));
    const len = dv.getUint32(p + 4, true);
    if (id === 'EXIF') {
      const b = d.subarray(p + 8, p + 8 + len);
      return latin1.decode(b.subarray(0, 6)) === 'Exif\0\0' ? b.subarray(6) : b;
    }
    p += 8 + len + (len & 1);                          // chunks are padded to even lengths
  }
  return null;
}

// The EXIF strings are written as "Workflow:{...}", so take the JSON out of the middle.
function jsonFrom(text) {
  if (!text) return null;
  const a = text.indexOf('{'), b = text.lastIndexOf('}');
  if (a < 0 || b < a) return null;
  try { return JSON.parse(text.slice(a, b + 1)); } catch (err) { return null; }
}

function isPng(d) { return d[0] === 0x89 && d[1] === 0x50 && d[2] === 0x4e && d[3] === 0x47; }
function isJpeg(d) { return d[0] === 0xff && d[1] === 0xd8; }
function isWebp(d) {
  return latin1.decode(d.subarray(0, 4)) === 'RIFF' && latin1.decode(d.subarray(8, 12)) === 'WEBP';
}

async function parseWorkflowFile(buf, name) {
  const d = new Uint8Array(buf);
  let texts = null;

  if (isPng(d)) {
    const t = await pngText(d);
    texts = [t.workflow, t.Workflow, t.prompt, t.Prompt, t.parameters];
  } else if (isJpeg(d)) {
    texts = exifStrings(jpegExif(d));
  } else if (isWebp(d)) {
    texts = exifStrings(webpExif(d));
  }

  if (texts) {
    const graphs = texts.map(jsonFrom).filter(Boolean);
    const workflow = graphs.find(g => Array.isArray(g.nodes));
    // With no UI graph, hand the first find to loadWorkflow so it explains the API format.
    if (workflow || graphs.length) return workflow || graphs[0];
    throw new Error('No ComfyUI workflow is embedded in ' + name + '.');
  }
  return JSON.parse(utf8.decode(buf));
}

function readFile(file) {
  file.arrayBuffer()
    .then(buf => parseWorkflowFile(buf, file.name))
    .then(data => loadWorkflow(data, file.name))
    .catch(err => toast(err.message || String(err), true));
}

const overlay = document.getElementById('overlay');
const dropEl = document.getElementById('drop');

['dragenter', 'dragover'].forEach(ev =>
  document.addEventListener(ev, e => {
    e.preventDefault();
    overlay.classList.add('dragover');
    dropEl.classList.add('dragging');
  }));

['dragleave', 'drop'].forEach(ev =>
  document.addEventListener(ev, e => {
    e.preventDefault();
    if (ev === 'dragleave' && e.relatedTarget) return;
    overlay.classList.remove('dragover');
    dropEl.classList.remove('dragging');
  }));

document.addEventListener('drop', e => {
  const file = e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files[0];
  if (file) readFile(file);
});

const fileInput = document.getElementById('file');
fileInput.addEventListener('change', () => {
  if (fileInput.files[0]) readFile(fileInput.files[0]);
  fileInput.value = '';
});

/* ---------------------------------------------------------------- UI wiring */

const reportPanel = document.getElementById('report');
const arrangePanel = document.getElementById('arrange');
const controlsPanel = document.getElementById('controls');
const btnReport = document.getElementById('btn-report');
const btnArrange = document.getElementById('btn-arrange');
const btnControls = document.getElementById('btn-controls');

function syncPanels() {
  btnReport.classList.toggle('on', !reportPanel.classList.contains('hidden'));
  btnArrange.classList.toggle('on', !arrangePanel.classList.contains('hidden'));
  btnControls.classList.toggle('on', !controlsPanel.classList.contains('hidden'));
}

btnReport.onclick = () => {
  const nowHidden = !reportPanel.classList.contains('hidden');
  reportPanel.classList.toggle('hidden', nowHidden);
  settings.packsPanelClosed = nowHidden;
  saveSettings();
  if (!nowHidden) renderReport();
  syncPanels();
};
document.getElementById('btn-report-close').onclick = () => {
  reportPanel.classList.add('hidden');
  settings.packsPanelClosed = true;
  saveSettings();
  syncPanels();
};

// the two left-hand panels share a slot, so opening one closes the other
btnArrange.onclick = () => {
  const show = arrangePanel.classList.contains('hidden');
  arrangePanel.classList.toggle('hidden', !show);
  if (show) controlsPanel.classList.add('hidden');
  syncPanels();
};
document.getElementById('btn-arrange-close').onclick = () => { arrangePanel.classList.add('hidden'); syncPanels(); };

btnControls.onclick = () => {
  const show = controlsPanel.classList.contains('hidden');
  controlsPanel.classList.toggle('hidden', !show);
  if (show) arrangePanel.classList.add('hidden');
  settings.controlsPanelClosed = !show;
  saveSettings();
  syncPanels();
};
document.getElementById('btn-controls-close').onclick = () => {
  controlsPanel.classList.add('hidden');
  settings.controlsPanelClosed = true;
  saveSettings();
  syncPanels();
};

// a click anywhere outside the menu dismisses it
document.addEventListener('pointerdown', e => {
  if (menuEls.length && !e.target.closest('.ctxmenu')) closeMenu();
}, true);
arrangePanel.querySelectorAll('button[data-act]').forEach(b => {
  b.onclick = () => arrange(b.dataset.act);
});

const chkHighlight = document.getElementById('chk-highlight');
const chkLabels = document.getElementById('chk-labels');
chkHighlight.checked = settings.highlight;
chkLabels.checked = settings.labels;
chkHighlight.onchange = e => { settings.highlight = e.target.checked; saveSettings(); dirty = true; };
chkLabels.onchange = e => { settings.labels = e.target.checked; saveSettings(); dirty = true; };

document.getElementById('report-body').addEventListener('click', e => {
  const b = e.target.closest('.copy-url');
  if (b) copyText(b.dataset.url, 'URL');
});

document.getElementById('btn-copy').onclick = () => {
  const text = reportText();
  if (!text) { toast('Nothing loaded', true); return; }
  copyText(text, 'Node pack list');
};

document.getElementById('btn-open').onclick = () => fileInput.click();
document.getElementById('btn-open2').onclick = () => fileInput.click();
document.getElementById('btn-save').onclick = save;
document.getElementById('btn-fit').onclick = fit;
document.getElementById('btn-reset').onclick = () => { view.scale = 1; dirty = true; };

addEventListener('resize', resize);
addEventListener('keydown', e => {
  const typing = /^(INPUT|TEXTAREA)$/.test(document.activeElement.tagName);
  if (typing) return;
  const plain = !e.ctrlKey && !e.metaKey && !e.altKey;
  if (e.key === 'f' && plain) fit();
  if ((e.key === 'c' || e.key === 'C') && plain) { e.preventDefault(); groupSelection(); }
  if (e.key === 'Escape') { selection = new Set(); selectedGroup = null; closeMenu(); dirty = true; }
  if ((e.key === 'Delete' || e.key === 'Backspace') && selectedGroup) {
    e.preventDefault();
    deleteGroup(selectedGroup);
  }
  if (e.key === 'a' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); selection = new Set(nodes); dirty = true; }
  if (e.key === 's' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); save(); }
});

if (!settings.packsPanelClosed) reportPanel.classList.remove('hidden');
if (!settings.controlsPanelClosed) controlsPanel.classList.remove('hidden');
syncPanels();
renderReport();

// ?workflow=<url> loads a file directly, handy for linking to a graph.
const qs = new URLSearchParams(location.search).get('workflow');
if (qs) {
  const qsName = qs.split('/').pop().split('?')[0];
  fetch(qs).then(r => r.arrayBuffer())
    .then(b => parseWorkflowFile(b, qsName))
    .then(d => loadWorkflow(d, qsName))
    .catch(err => toast('Could not load ' + qs + ': ' + err.message, true));
}

// Small hook so the viewer can be scripted or tested from the console.
window.comfyview = {
  get view() { return view; },
  get nodes() { return nodes; },
  get groups() { return groups; },
  get selection() { return selection; },
  get report() { return report; },
  toScreen: (gx, gy) => [gx * view.scale + view.x, gy * view.scale + view.y],
  arrange,
  fit,
  save,
  groupSelection,
  startRename,
  deleteGroup,
  fitGroupTo,
  openMenu,
  closeMenu,
  recolorNodes,
  recolorGroup,
  get selectedGroup() { return selectedGroup; },
};

resize();
draw();
})();
