#!/usr/bin/env python3
"""Regenerate nodedb.js : the node-type -> node-pack database used by ComfyView.

Two sources:
  * core node types: NODE_CLASS_MAPPINGS in ComfyUI's nodes.py and comfy_extras/*.py
  * custom node packs: ComfyUI-Manager's extension-node-map.json

Usage:  python tools/build-nodedb.py
Writes: nodedb.js  (window.COMFY_NODE_DB)
"""

import json
import os
import re
import sys
import urllib.request
from concurrent.futures import ThreadPoolExecutor

COMFY_RAW = 'https://raw.githubusercontent.com/comfyanonymous/ComfyUI/master/'
EXTRAS_API = 'https://api.github.com/repos/comfyanonymous/ComfyUI/contents/comfy_extras'
NODE_MAP = 'https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json'

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Nodes the frontend provides itself : they appear in workflows but have no python class.
FRONTEND_NODES = [
    'Note', 'MarkdownNote', 'Reroute', 'PrimitiveNode',
    'PrimitiveInt', 'PrimitiveFloat', 'PrimitiveString',
    'PrimitiveStringMultiline', 'PrimitiveBoolean',
]

KEY = re.compile(r'"([^"\n]{1,80})"\s*:')


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': 'comfyview-builder'})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode('utf-8', 'ignore')


def dict_blocks(src, name):
    """Return the bodies of every `name = { ... }` assignment in src."""
    out = []
    for m in re.finditer(re.escape(name) + r'\s*(?::[^=\n]*)?=\s*\{', src):
        start = m.end() - 1
        depth = 0
        for j in range(start, len(src)):
            if src[j] == '{':
                depth += 1
            elif src[j] == '}':
                depth -= 1
                if depth == 0:
                    out.append(src[start:j])
                    break
    return out


def core_types():
    print('fetching ComfyUI core nodes…')
    sources = [get(COMFY_RAW + 'nodes.py')]
    names = [f['name'] for f in json.loads(get(EXTRAS_API)) if f['name'].endswith('.py')]
    with ThreadPoolExecutor(8) as pool:
        sources += list(pool.map(lambda n: get(COMFY_RAW + 'comfy_extras/' + n), names))
    print(f'  {len(sources)} source files')

    found = set()
    for src in sources:
        for key in ('NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'):
            for body in dict_blocks(src, key):
                found |= set(KEY.findall(body))
        found |= set(re.findall(r'NODE_CLASS_MAPPINGS\["([^"]+)"\]', src))
        # V3 schema nodes declare their type as node_id="…"
        found |= set(re.findall(r'node_id\s*=\s*"([^"]+)"', src))

    found |= set(FRONTEND_NODES)
    found = {t for t in found if t and not t.startswith(('http', '_'))}
    print(f'  {len(found)} core node types')
    return found


def packs_and_nodes(core):
    print('fetching ComfyUI-Manager extension map…')
    data = json.loads(get(NODE_MAP))
    print(f'  {len(data)} repositories')

    packs, nodes, remap = [], {}, {}
    for url, entry in data.items():
        try:
            names, meta = entry[0], entry[1] or {}
        except Exception:
            continue
        if not isinstance(names, list):
            continue
        names = [n for n in names if isinstance(n, str) and n and n not in core]
        if not names:
            continue
        title = meta.get('title_aux') or url.rstrip('/').split('/')[-1].removesuffix('.git')
        short = url.replace('https://github.com/', 'gh:')
        idx = len(packs)
        packs.append([title, short])
        for n in names:
            cur = nodes.get(n)
            if cur is None:
                nodes[n] = idx
            elif isinstance(cur, int):
                if cur != idx:
                    nodes[n] = [cur, idx]
            elif idx not in cur:
                cur.append(idx)
    print(f'  {len(packs)} packs, {len(nodes)} custom node types')
    return packs, nodes


def main():
    core = core_types()
    packs, nodes = packs_and_nodes(core)
    db = {'core': sorted(core), 'packs': packs, 'nodes': nodes}
    out = os.path.join(ROOT, 'nodedb.js')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/build-nodedb.py. Do not edit by hand. */\n')
        f.write('window.COMFY_NODE_DB=' + json.dumps(db, separators=(',', ':')) + ';\n')
    print(f'wrote {out} ({os.path.getsize(out) // 1024} KB)')


if __name__ == '__main__':
    sys.exit(main())
